import type { SiteConfig } from '@/types';

/**
 * Studio-wide constants. Everything the layout, footer and metadata need,
 * in one place, so placeholder copy can be swapped for final copy without
 * touching component code.
 */
export const siteConfig: SiteConfig = {
  name: 'Thoorigai Prints',
  shortName: 'Thoorigai',
  tagline: 'A printing house, not a print shop.',
  description:
    'Digital and offset printing, packaging and binding, produced in Chennai since 2017. Short runs and long runs, finished to a standard you can hold up to the light.',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.thoorigaiprints.com',
  locale: 'en_IN',
  founded: 2017,

  contact: {
    // TODO: three different numbers are live on the current site.
    // Confirm the canonical one with the studio before launch.
    phone: '+91 99626 04017',
    whatsapp: '+91 77082 98673',
    email: 'sales@thoorigaiprints.com',
    address: {
      street: 'Nayar Vardha Pillai St, Balaji Nagar, Royapettah',
      city: 'Chennai',
      state: 'Tamil Nadu',
      postalCode: '600014',
      country: 'India',
    },
    hours: 'Mon–Sat, 9:30am – 7:00pm IST',
    // The same window, in the shape schema.org wants. `hours` above is for
    // people; this is for Google. Change one and change the other.
    hoursSpec: {
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      opens: '09:30',
      closes: '19:00',
    },
    // TODO: placeholder. This promise now appears beside every CTA on the
    // site, so confirm the real turnaround with the studio before launch.
    responseTime: 'Most briefs are answered the same working day.',
  },

  social: [
    { label: 'Instagram', href: 'https://instagram.com/', icon: 'instagram' },
    { label: 'Facebook', href: 'https://facebook.com/', icon: 'facebook' },
    { label: 'LinkedIn', href: 'https://linkedin.com/', icon: 'linkedin' },
  ],

  /**
   * Generated by `src/app/opengraph-image.tsx`. Used for JSON-LD; the social
   * cards themselves come from the file convention automatically.
   */
  ogImage: '/opengraph-image',
};

/** Numbers worth stating plainly. Placeholder values — confirm with the studio. */
export const studioStats = [
  { value: '2017', label: 'Founded in Chennai' },
  { value: '1,200+', label: 'Jobs on press each year' },
  { value: '48hr', label: 'Typical digital turnaround' },
  { value: '9', label: 'Binding formats in house' },
] as const;

export default siteConfig;
